sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t jck9116/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true jck9116/react-test npm test

after_success:
  - docker build -t jck9116/multi-client ./client
  - docker build -t jck9116/multi-nginx ./nginx
  - docker build -t jck9116/multi-server ./server
  - docker build -t jck9116/multi-worker ./worker
  # Log in to the docker CLI--dockerhub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push jck9116/multi-client
  - docker push jck9116/multi-nginx
  - docker push jck9116/multi-server
  - docker push jck9116/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "ca-central-1"
  app: "multi-docker"
  env: "Multidocker-env"
  bucket_name: "elasticbeanstalk-ca-central-1-649259202218"
  bucket_path: "multidocker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY